USE MyGuitarShop
GO
CREATE INDEX I_Zip ON Addresses(ZipCode)
GO

USE master
GO

IF DB_ID('MyWebDB') IS NOT NULL
DROP DATABASE MyWebDB
GO

CREATE DATABASE MyWebDB
GO

USE MyWebDB
GO

CREATE TABLE Users (
	UserID INT NOT NULL IDENTITY PRIMARY KEY,
	FirstName VARCHAR(255),
	LastName VARCHAR(255) NOT NULL)

CREATE TABLE Products (
	ProductID INT NOT NULL IDENTITY PRIMARY KEY,
	ProductName VARCHAR(255) NOT NULL)

CREATE TABLE Downloads (
	DownloadID INT NOT NULL IDENTITY PRIMARY KEY,
	UserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
	DownloadDate DATETIME NOT NULL,
	DownloadName VARCHAR(255) NOT NULL, --FileName was a Reserved keyword
	ProductID INT NOT NULL FOREIGN KEY REFERENCES Products (ProductID))

CREATE INDEX IF_UserID ON Downloads (UserID)

CREATE INDEX IF_ProductID ON Downloads (ProductID)

ALTER TABLE Products ADD ProductPrice DECIMAL(5,2) DEFAULT 9.99

ALTER TABLE Products ADD DateAdded DATETIME

ALTER TABLE Users
	ALTER COLUMN FirstName VARCHAR(20)
ALTER TABLE Users
	ADD CHECK (FirstName IS NOT NULL)
GO